fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    body_listener: true
    routing_loader: true
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
    view:
        view_response_listener:  'force'
    format_listener:
        rules:
            - { path: '^/api', prefer_extension: true, fallback_format: json, priorities: [ json ] }
    zone:
        - { path: ^/api(?!/doc$) }